# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "my_jaffle_shop"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "my_jaffle_shop"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  my_jaffle_shop:
    # Applies to all files under models/staging/
    staging:
      jaffle_shop:
        +materialized: view
      stripe:
        +materialized: view
    # Marts are downstramed tables and used for BI
    # Materialize them as tables to avoid executing views every time they are used
    marts:
      +materialized: table

# views are good for staging layer because they are cheap to create and always up to date (created each time dbt build is run)
# tables are good for marts because they are faster to query and can be materialized (created once and overwritten with every dbt run)

# + sign means that the configuration applies to all models in the directory

